# Generated by Django 4.1.1 on 2023-07-16 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0002_employeeuploadfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeuploadfile',
            name='upload_file',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
    ]
